### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by indy-vijay** [rfdy/imagemagick#1]
I installed the RFD ImageMagick Library using

composer require rfd/imagemagick
I went through the readme and this is how they have done it

use Rfd\ImageMagick;
use Rfd\ImageMagick\CLI\OperationFactory();
use Rfd\ImageMagick\Image\File;
use Rfd\ImageMagick\Options\CommonOptions;

$im = new ImageMagick(new OperationFactory());
It throws Class 'Rfd\ImageMagick' not found error. But that error goes away when I do
use Rfd\ImageMagick\ImageMagick;

The statement below throws an error but works with the () at the end
use Rfd\ImageMagick\CLI\OperationFactory();
Now its giving OperationFactory not found error. I can't find that class anywhere in the install so I'm really confused! Any help would be really appreciated. I'm trying to generate PDF thumnail image previews using this library.

**Comment by lawsontyler** [comment]
You're right, there's an issue with the documentation.  I've updated the README.md file, that line is now:

```
use Rfd\ImageMagick\CLI\Operation\Factory as OperationFactory;
```

**Comment by indy-vijay** [comment]
Thanks! There was one more issue though
use Rfd\ImageMagick; also gave a class not found error so I had to do
use Rfd\ImageMagick\ImageMagick;
Maybe its with the PHP version, I'm not sure. Mine is 5.5.27
