### ISSUE TITLE
Creating PDF thumbnail preview image

### ISSUE THREAD

**Issue by indy-vijay** [rfdy/imagemagick#2]
Is it possible to create a PDF thumbnail preview image (of the first page) using this? If yes, can you guide me in the right direction?

**Comment by lawsontyler** [comment]
I've just pushed 1.2.0, which includes SequenceNumber and Density.

```
$image = new File('your_filename.pdf');
$output_image = new File('output_image.png');

$this->imagemagick->getOperationBuilder($image)
            ->convert(CommonOptions::FORMAT_PNG)
            ->sequenceNumber(1) // Gets the *second* page; this is 0-based.
            ->density(300) // Pixel density when rasterizing vector images.
            ->finish($output_image);
```

This should allow you to convert PDFs.  Don't forget to have ghostscript installed, or else ImageMagick won't be able to read the PDF.

**Comment by indy-vijay** [comment]
Awesome!
